specVersion: 1.0.0
indexerHints:
  prune: auto
schema:
  file: ./schema.graphql
dataSources:
  # MainController
  - kind: ethereum
    name: MainController
    network: base
    source:
      address: "0x1337F001E280420EcCe9E7B934Fa07D67fdb62CD"
      abi: MainController
      startBlock: 20980674
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        # - AddMarket
        # - SetDelegateApproval
        # - SetDelegationEnabled
        # - SetProtocolEnabled
        # - SetImplementations
        # - AddMarketHook
        # - RemoveMarketHook
        # - HookDebtAjustment
        # - AddMonetaryPolicy
        # - ChangeMonetaryPolicy
        # - ChangeMonetaryPolicyForMarket
        # - SetGlobalMarketDebtCeiling
        # - SetPegKeeperRegulator
        - CreateLoan
        - AdjustLoan
        - CloseLoan
        - LiquidateLoan
        # - CollectAmmFees
        # - CollectFees
      abis:
        - name: MainController
          file: ./abis/cdp/MainController.json
      eventHandlers:
        # - event: AddMarket(indexed address,address,address,uint256)
        #   handler: handleAddMarket
        # - event: SetDelegateApproval(indexed address,indexed address,bool)
        #   handler: handleSetDelegateApproval
        # - event: SetDelegationEnabled(address,bool)
        #   handler: handleSetDelegationEnabled
        # - event: SetProtocolEnabled(address,bool)
        #   handler: handleSetProtocolEnabled
        # - event: SetImplementations(indexed uint256,address,address)
        #   handler: handleSetImplementations
        # - event: AddMarketHook(indexed address,indexed address,uint256,bool[4])
        #   handler: handleAddMarketHook
        # - event: RemoveMarketHook(indexed address,indexed address,uint256)
        #   handler: handleRemoveMarketHook
        # - event: HookDebtAjustment(indexed address,indexed address,int256,uint256,uint256)
        #   handler: handleHookDebtAjustment
        # - event: AddMonetaryPolicy(indexed uint256,address)
        #   handler: handleAddMonetaryPolicy
        # - event: ChangeMonetaryPolicy(indexed uint256,address)
        #   handler: handleChangeMonetaryPolicy
        # - event: ChangeMonetaryPolicyForMarket(indexed address,indexed uint256)
        #   handler: handleChangeMonetaryPolicyForMarket
        # - event: SetGlobalMarketDebtCeiling(uint256)
        #   handler: handleSetGlobalMarketDebtCeiling
        # - event: SetPegKeeperRegulator(address,bool)
        #   handler: handleSetPegKeeperRegulator
        - event: CreateLoan(indexed address,indexed address,indexed address,uint256,uint256)
          handler: handleCreateLoan
        - event: AdjustLoan(indexed address,indexed address,indexed address,int256,int256)
          handler: handleAdjustLoan
        - event: CloseLoan(indexed address,indexed address,indexed address,uint256,uint256,uint256)
          handler: handleCloseLoan
        - event: LiquidateLoan(indexed address,indexed address,indexed address,uint256,uint256,uint256)
          handler: handleLiquidateLoan
        # - event: CollectAmmFees(indexed address,uint256,uint256)
        #   handler: handleCollectAmmFees
        # - event: CollectFees(uint256,uint256,uint256,uint256)
        #   handler: handleCollectFees
      file: ./src/cdp/MainController.ts

  # BridgeToken
  - kind: ethereum
    name: BridgeToken
    network: base
    source:
      address: "0x69420f9E38a4e60a62224C489be4BF7a94402496"
      abi: BridgeToken
      startBlock: 20980310
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        # - Approval
        # - BridgeEnabledSet
        # - EIP712DomainChanged
        # - EnforcedOptionSet
        # - FlashMintEnabledSet
        # - MinterSet
        # - MsgInspectorSet
        - OFTReceived
        - OFTSent
        # - OwnershipTransferred
        # - PeerSet
        # - PreCrimeSet
        # - Transfer
      abis:
        - name: BridgeToken
          file: ./abis/BridgeToken.json
      eventHandlers:
        # - event: Approval(indexed address,indexed address,uint256)
        #   handler: handleApproval
        # - event: BridgeEnabledSet(address,bool)
        #   handler: handleBridgeEnabledSet
        # - event: EIP712DomainChanged()
        #   handler: handleEIP712DomainChanged
        # - event: EnforcedOptionSet((uint32,uint16,bytes)[])
        #   handler: handleEnforcedOptionSet
        # - event: FlashMintEnabledSet(address,bool)
        #   handler: handleFlashMintEnabledSet
        # - event: MinterSet(address,bool)
        #   handler: handleMinterSet
        # - event: MsgInspectorSet(address)
        #   handler: handleMsgInspectorSet
        - event: OFTReceived(indexed bytes32,uint32,indexed address,uint256)
          handler: handleOFTReceived
        - event: OFTSent(indexed bytes32,uint32,indexed address,uint256,uint256)
          handler: handleOFTSent
        # - event: OwnershipTransferred(indexed address,indexed address)
        #   handler: handleOwnershipTransferred
        # - event: PeerSet(uint32,bytes32)
        #   handler: handlePeerSet
        # - event: PreCrimeSet(address)
        #   handler: handlePreCrimeSet
        # - event: Transfer(indexed address,indexed address,uint256)
        #   handler: handleTransfer
      file: ./src/BridgeToken.ts


  # AMMs
  - kind: ethereum
    name: AMM-0
    network: base
    source:
      address: "0x65958eB6169B291aeeE5e5445674FB4868476878"
      abi: AMM
      startBlock: 21117767
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - TokenExchange
        - DepositAMM
        - WithdrawAMM
        - SetRate
      abis:
        - name: AMM
          file: ./abis/cdp/AMM.json
      eventHandlers:
        - event: TokenExchange(indexed address,uint256,uint256,uint256,uint256)
          handler: handleTokenExchange
        - event: Deposit(indexed address,uint256,int256,int256)
          handler: handleDeposit
        - event: Withdraw(indexed address,uint256,uint256)
          handler: handleWithdraw
        - event: SetRate(uint256,uint256,uint256)
          handler: handleSetRate
      file: ./src/cdp/AMM.ts
  - kind: ethereum
    name: AMM-1
    network: base
    source:
      address: "0x09A00B732C0A9567A088f6433f77211b05D4DBb8"
      abi: AMM
      startBlock: 21118463
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - TokenExchange
        - DepositAMM
        - WithdrawAMM
        - SetRate
      abis:
        - name: AMM
          file: ./abis/cdp/AMM.json
      eventHandlers:
        - event: TokenExchange(indexed address,uint256,uint256,uint256,uint256)
          handler: handleTokenExchange
        - event: Deposit(indexed address,uint256,int256,int256)
          handler: handleDeposit
        - event: Withdraw(indexed address,uint256,uint256)
          handler: handleWithdraw
        - event: SetRate(uint256,uint256,uint256)
          handler: handleSetRate
      file: ./src/cdp/AMM.ts
  - kind: ethereum
    name: AMM-2
    network: base
    source:
      address: "0xC65949105c75d517C6c63d6d96F4837124ccac10"
      abi: AMM
      startBlock: 21118623
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - TokenExchange
        - DepositAMM
        - WithdrawAMM
        - SetRate
      abis:
        - name: AMM
          file: ./abis/cdp/AMM.json
      eventHandlers:
        - event: TokenExchange(indexed address,uint256,uint256,uint256,uint256)
          handler: handleTokenExchange
        - event: Deposit(indexed address,uint256,int256,int256)
          handler: handleDeposit
        - event: Withdraw(indexed address,uint256,uint256)
          handler: handleWithdraw
        - event: SetRate(uint256,uint256,uint256)
          handler: handleSetRate
      file: ./src/cdp/AMM.ts
  - kind: ethereum
    name: AMM-3
    network: base
    source:
      address: "0x9E4bEf7995db8ADD5B6468B5AeFADc90d80cFB76"
      abi: AMM
      startBlock: 22111792
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - TokenExchange
        - DepositAMM
        - WithdrawAMM
        - SetRate
      abis:
        - name: AMM
          file: ./abis/cdp/AMM.json
      eventHandlers:
        - event: TokenExchange(indexed address,uint256,uint256,uint256,uint256)
          handler: handleTokenExchange
        - event: Deposit(indexed address,uint256,int256,int256)
          handler: handleDeposit
        - event: Withdraw(indexed address,uint256,uint256)
          handler: handleWithdraw
        - event: SetRate(uint256,uint256,uint256)
          handler: handleSetRate
      file: ./src/cdp/AMM.ts

  # BoostedStakers
  - kind: ethereum
    name: BoostedStaker-0
    network: base
    source:
      address: "0x9F04112af02CE57C10d946481Ea06373719c1E7E"
      abi: BoostedStaker
      startBlock: 21076336
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        # - AccountWeightUpdated
        # - ApprovedUnstakerSet
        # - LocksDisabled
        - Staked
        - Unstaked
      abis:
        - name: BoostedStaker
          file: ./abis/BoostedStaker.json
      eventHandlers:
        # - event: AccountWeightUpdated(indexed address,indexed uint256,uint256,uint256)
        #   handler: handleAccountWeightUpdated
        # - event: ApprovedUnstakerSet(indexed address,indexed address,bool)
        #   handler: handleApprovedUnstakerSet
        # - event: LocksDisabled()
        #   handler: handleLocksDisabled
        - event: Staked(indexed address,indexed uint256,uint256,uint256,bool)
          handler: handleStaked
        - event: Unstaked(indexed address,indexed uint256,uint256,uint256)
          handler: handleUnstaked
      file: ./src/BoostedStaker.ts
  - kind: ethereum
    name: BoostedStaker-1
    network: base
    source:
      address: "0xe0f7c023763d782970ab45e9232255a64290cd6a"
      abi: BoostedStaker
      startBlock: 21076680
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        # - AccountWeightUpdated
        # - ApprovedUnstakerSet
        # - LocksDisabled
        - Staked
        - Unstaked
      abis:
        - name: BoostedStaker
          file: ./abis/BoostedStaker.json
      eventHandlers:
        # - event: AccountWeightUpdated(indexed address,indexed uint256,uint256,uint256)
        #   handler: handleAccountWeightUpdated
        # - event: ApprovedUnstakerSet(indexed address,indexed address,bool)
        #   handler: handleApprovedUnstakerSet
        # - event: LocksDisabled()
        #   handler: handleLocksDisabled
        - event: Staked(indexed address,indexed uint256,uint256,uint256,bool)
          handler: handleStaked
        - event: Unstaked(indexed address,indexed uint256,uint256,uint256)
          handler: handleUnstaked
      file: ./src/BoostedStaker.ts
  - kind: ethereum
    name: BoostedStaker-2
    network: base
    source:
      address: "0xb7698c690752ae034e914a29a0de67339a94982b"
      abi: BoostedStaker
      startBlock: 21076557
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        # - AccountWeightUpdated
        # - ApprovedUnstakerSet
        # - LocksDisabled
        - Staked
        - Unstaked
      abis:
        - name: BoostedStaker
          file: ./abis/BoostedStaker.json
      eventHandlers:
        # - event: AccountWeightUpdated(indexed address,indexed uint256,uint256,uint256)
        #   handler: handleAccountWeightUpdated
        # - event: ApprovedUnstakerSet(indexed address,indexed address,bool)
        #   handler: handleApprovedUnstakerSet
        # - event: LocksDisabled()
        #   handler: handleLocksDisabled
        - event: Staked(indexed address,indexed uint256,uint256,uint256,bool)
          handler: handleStaked
        - event: Unstaked(indexed address,indexed uint256,uint256,uint256)
          handler: handleUnstaked
      file: ./src/BoostedStaker.ts
  - kind: ethereum
    name: BoostedStaker-3
    network: base
    source:
      address: "0x45acdee3c9f7e1c7ad6cc10c9cb9f74eb52d0e70"
      abi: BoostedStaker
      startBlock: 21076574
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        # - AccountWeightUpdated
        # - ApprovedUnstakerSet
        # - LocksDisabled
        - Staked
        - Unstaked
      abis:
        - name: BoostedStaker
          file: ./abis/BoostedStaker.json
      eventHandlers:
        # - event: AccountWeightUpdated(indexed address,indexed uint256,uint256,uint256)
        #   handler: handleAccountWeightUpdated
        # - event: ApprovedUnstakerSet(indexed address,indexed address,bool)
        #   handler: handleApprovedUnstakerSet
        # - event: LocksDisabled()
        #   handler: handleLocksDisabled
        - event: Staked(indexed address,indexed uint256,uint256,uint256,bool)
          handler: handleStaked
        - event: Unstaked(indexed address,indexed uint256,uint256,uint256)
          handler: handleUnstaked
      file: ./src/BoostedStaker.ts
  - kind: ethereum
    name: BoostedStaker-4
    network: base
    source:
      address: "0xbedd35f23ea055c6af039f9c6a6fc8bdee4d7a13"
      abi: BoostedStaker
      startBlock: 21073398
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        # - AccountWeightUpdated
        # - ApprovedUnstakerSet
        # - LocksDisabled
        - Staked
        - Unstaked
      abis:
        - name: BoostedStaker
          file: ./abis/BoostedStaker.json
      eventHandlers:
        # - event: AccountWeightUpdated(indexed address,indexed uint256,uint256,uint256)
        #   handler: handleAccountWeightUpdated
        # - event: ApprovedUnstakerSet(indexed address,indexed address,bool)
        #   handler: handleApprovedUnstakerSet
        # - event: LocksDisabled()
        #   handler: handleLocksDisabled
        - event: Staked(indexed address,indexed uint256,uint256,uint256,bool)
          handler: handleStaked
        - event: Unstaked(indexed address,indexed uint256,uint256,uint256)
          handler: handleUnstaked
      file: ./src/BoostedStaker.ts
