name: 'Delete Subgraph'
description: 'Delete a specific version of a subgraph in Goldsky'
inputs:
  network:
    description: 'Network (optimism or arbitrum or base)'
    required: true
  goldsky_api_key:
    description: 'Goldsky API Key'
    required: true
  version:
    description: 'Version of the subgraph to delete (e.g., 1.0.0, must be SemVer)'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Goldsky CLI
      shell: bash
      run: npm install -g @goldskycom/cli

    - name: Delete Subgraph Version
      shell: bash
      env:
        GOLDSKY_API_KEY: ${{ inputs.goldsky_api_key }}
      run: |
        goldsky subgraph delete defi-money-${{ inputs.network }}/${{ inputs.version }} --force --token $GOLDSKY_API_KEY 