specVersion: 1.0.0
indexerHints:
  prune: auto
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: MainController
    network: optimism
    source:
      address: "0x1337F001E280420EcCe9E7B934Fa07D67fdb62CD"
      abi: MainController
      startBlock: 121875837
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        # - AddMarket
        # - SetDelegateApproval
        # - SetDelegationEnabled
        # - SetProtocolEnabled
        # - SetImplementations
        # - AddMarketHook
        # - RemoveMarketHook
        # - HookDebtAjustment
        # - AddMonetaryPolicy
        # - ChangeMonetaryPolicy
        # - ChangeMonetaryPolicyForMarket
        # - SetGlobalMarketDebtCeiling
        # - SetPegKeeperRegulator
        - CreateLoan
        - AdjustLoan
        - CloseLoan
        - LiquidateLoan
        # - CollectAmmFees
        # - CollectFees
      abis:
        - name: MainController
          file: ./abis/cdp/MainController.json
      eventHandlers:
        # - event: AddMarket(indexed address,address,address,uint256)
        #   handler: handleAddMarket
        # - event: SetDelegateApproval(indexed address,indexed address,bool)
        #   handler: handleSetDelegateApproval
        # - event: SetDelegationEnabled(address,bool)
        #   handler: handleSetDelegationEnabled
        # - event: SetProtocolEnabled(address,bool)
        #   handler: handleSetProtocolEnabled
        # - event: SetImplementations(indexed uint256,address,address)
        #   handler: handleSetImplementations
        # - event: AddMarketHook(indexed address,indexed address,uint256,bool[4])
        #   handler: handleAddMarketHook
        # - event: RemoveMarketHook(indexed address,indexed address,uint256)
        #   handler: handleRemoveMarketHook
        # - event: HookDebtAjustment(indexed address,indexed address,int256,uint256,uint256)
        #   handler: handleHookDebtAjustment
        # - event: AddMonetaryPolicy(indexed uint256,address)
        #   handler: handleAddMonetaryPolicy
        # - event: ChangeMonetaryPolicy(indexed uint256,address)
        #   handler: handleChangeMonetaryPolicy
        # - event: ChangeMonetaryPolicyForMarket(indexed address,indexed uint256)
        #   handler: handleChangeMonetaryPolicyForMarket
        # - event: SetGlobalMarketDebtCeiling(uint256)
        #   handler: handleSetGlobalMarketDebtCeiling
        # - event: SetPegKeeperRegulator(address,bool)
        #   handler: handleSetPegKeeperRegulator
        - event: CreateLoan(indexed address,indexed address,indexed address,uint256,uint256)
          handler: handleCreateLoan
        - event: AdjustLoan(indexed address,indexed address,indexed address,int256,int256)
          handler: handleAdjustLoan
        - event: CloseLoan(indexed address,indexed address,indexed address,uint256,uint256,uint256)
          handler: handleCloseLoan
        - event: LiquidateLoan(indexed address,indexed address,indexed address,uint256,uint256,uint256)
          handler: handleLiquidateLoan
        # - event: CollectAmmFees(indexed address,uint256,uint256)
        #   handler: handleCollectAmmFees
        # - event: CollectFees(uint256,uint256,uint256,uint256)
        #   handler: handleCollectFees
      file: ./src/cdp/MainController.ts
# StableStaker
  - kind: ethereum
    name: StableStaker
    network: optimism
    source:
      address: "0x4626C0D31c52991573DDd4dF8F2bB1Bc5101284F"
      abi: StableStaker
      startBlock: 126317235
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        # - Approval
        # - BridgeEnabledSet
        - Cooldown
        # - CooldownDurationUpdated
        - Deposit
        # - EnforcedOptionSet
        # - FeeAggregatorSet
        # - GovStakerSet
        # - MsgInspectorSet
        # - NewRewardPeriod
        # - NotifyNewFees
        # - OFTReceived
        # - OFTSent
        # - OwnershipTransferred
        # - PeerSet
        # - PreCrimeSet
        # - RewardRegulatorSet
        - Transfer
        - Unstake
      abis:
        - name: StableStaker
          file: ./abis/StableStaker.json
      eventHandlers:
        # - event: Approval(indexed address,indexed address,uint256)
        #   handler: handleApproval
        # - event: BridgeEnabledSet(address,bool)
        #   handler: handleBridgeEnabledSet
        - event: Cooldown(indexed address,uint256,uint256,uint256)
          handler: handleCooldown
        # - event: CooldownDurationUpdated(uint32)
        #   handler: handleCooldownDurationUpdated
        - event: Deposit(indexed address,indexed address,uint256,uint256)
          handler: handleDeposit
        # - event: EnforcedOptionSet((uint32,uint16,bytes)[])
        #   handler: handleEnforcedOptionSet
        # - event: FeeAggregatorSet(address)
        #   handler: handleFeeAggregatorSet
        # - event: GovStakerSet(address)
        #   handler: handleGovStakerSet
        # - event: MsgInspectorSet(address)
        #   handler: handleMsgInspectorSet
        # - event: NewRewardPeriod(uint256,uint256,uint256,uint256)
        #   handler: handleNewRewardPeriod
        # - event: NotifyNewFees(uint256)
        #   handler: handleNotifyNewFees
        # - event: OFTReceived(indexed bytes32,uint32,indexed address,uint256)
        #   handler: handleOFTReceived
        # - event: OFTSent(indexed bytes32,uint32,indexed address,uint256,uint256)
        #   handler: handleOFTSent
        # - event: OwnershipTransferred(indexed address,indexed address)
        #   handler: handleOwnershipTransferred
        # - event: PeerSet(uint32,bytes32)
        #   handler: handlePeerSet
        # - event: PreCrimeSet(address)
        #   handler: handlePreCrimeSet
        # - event: RewardRegulatorSet(address)
        #   handler: handleRewardRegulatorSet
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        - event: Unstake(indexed address,indexed address,uint256)
          handler: handleUnstake
      file: ./src/StableStaker.ts

# BridgeToken
  - kind: ethereum
    name: BridgeToken
    network: optimism
    source:
      address: "0x69420f9E38a4e60a62224C489be4BF7a94402496"
      abi: BridgeToken
      startBlock: 121875828
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        # - Approval
        # - BridgeEnabledSet
        # - EIP712DomainChanged
        # - EnforcedOptionSet
        # - FlashMintEnabledSet
        # - MinterSet
        # - MsgInspectorSet
        - OFTReceived
        - OFTSent
        # - OwnershipTransferred
        # - PeerSet
        # - PreCrimeSet
        # - Transfer
      abis:
        - name: BridgeToken
          file: ./abis/BridgeToken.json
      eventHandlers:
        # - event: Approval(indexed address,indexed address,uint256)
        #   handler: handleApproval
        # - event: BridgeEnabledSet(address,bool)
        #   handler: handleBridgeEnabledSet
        # - event: EIP712DomainChanged()
        #   handler: handleEIP712DomainChanged
        # - event: EnforcedOptionSet((uint32,uint16,bytes)[])
        #   handler: handleEnforcedOptionSet
        # - event: FlashMintEnabledSet(address,bool)
        #   handler: handleFlashMintEnabledSet
        # - event: MinterSet(address,bool)
        #   handler: handleMinterSet
        # - event: MsgInspectorSet(address)
        #   handler: handleMsgInspectorSet
        - event: OFTReceived(indexed bytes32,uint32,indexed address,uint256)
          handler: handleOFTReceived
        - event: OFTSent(indexed bytes32,uint32,indexed address,uint256,uint256)
          handler: handleOFTSent
        # - event: OwnershipTransferred(indexed address,indexed address)
        #   handler: handleOwnershipTransferred
        # - event: PeerSet(uint32,bytes32)
        #   handler: handlePeerSet
        # - event: PreCrimeSet(address)
        #   handler: handlePreCrimeSet
        # - event: Transfer(indexed address,indexed address,uint256)
        #   handler: handleTransfer
      file: ./src/BridgeToken.ts

# AMMs
  - kind: ethereum
    name: AMM-0
    network: optimism
    source:
      address: "0xad7d46ceB08ba5a1A21AFc43e9E2591c842F9057"
      abi: AMM
      startBlock: 121876298
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - TokenExchange
        - DepositAMM
        - WithdrawAMM
        - SetRate
      abis:
        - name: AMM
          file: ./abis/cdp/AMM.json
      eventHandlers:
        - event: TokenExchange(indexed address,uint256,uint256,uint256,uint256)
          handler: handleTokenExchange
        - event: Deposit(indexed address,uint256,int256,int256)
          handler: handleDeposit
        - event: Withdraw(indexed address,uint256,uint256)
          handler: handleWithdraw
        - event: SetRate(uint256,uint256,uint256)
          handler: handleSetRate
      file: ./src/cdp/AMM.ts
  - kind: ethereum
    name: AMM-1
    network: optimism
    source:
      address: "0x69B308628D58066Dd21874B43CB790BaE3D0BaFC"
      abi: AMM
      startBlock: 121876319
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - TokenExchange
        - DepositAMM
        - WithdrawAMM
        - SetRate
      abis:
        - name: AMM
          file: ./abis/cdp/AMM.json
      eventHandlers:
        - event: TokenExchange(indexed address,uint256,uint256,uint256,uint256)
          handler: handleTokenExchange
        - event: Deposit(indexed address,uint256,int256,int256)
          handler: handleDeposit
        - event: Withdraw(indexed address,uint256,uint256)
          handler: handleWithdraw
        - event: SetRate(uint256,uint256,uint256)
          handler: handleSetRate
      file: ./src/cdp/AMM.ts
  - kind: ethereum
    name: AMM-2
    network: optimism
    source:
      address: "0x2eEAb5f076dea85517a53b33f4828c5bb6CE9216"
      abi: AMM
      startBlock: 121876336
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - TokenExchange
        - DepositAMM
        - WithdrawAMM
        - SetRate
      abis:
        - name: AMM
          file: ./abis/cdp/AMM.json
      eventHandlers:
        - event: TokenExchange(indexed address,uint256,uint256,uint256,uint256)
          handler: handleTokenExchange
        - event: Deposit(indexed address,uint256,int256,int256)
          handler: handleDeposit
        - event: Withdraw(indexed address,uint256,uint256)
          handler: handleWithdraw
        - event: SetRate(uint256,uint256,uint256)
          handler: handleSetRate
      file: ./src/cdp/AMM.ts
  - kind: ethereum
    name: AMM-3
    network: optimism
    source:
      address: "0xAA948FcF8954E4721B39eaAD32978E804A5A0859"
      abi: AMM
      startBlock: 125175383
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - TokenExchange
        - DepositAMM
        - WithdrawAMM
        - SetRate
      abis:
        - name: AMM
          file: ./abis/cdp/AMM.json
      eventHandlers:
        - event: TokenExchange(indexed address,uint256,uint256,uint256,uint256)
          handler: handleTokenExchange
        - event: Deposit(indexed address,uint256,int256,int256)
          handler: handleDeposit
        - event: Withdraw(indexed address,uint256,uint256)
          handler: handleWithdraw
        - event: SetRate(uint256,uint256,uint256)
          handler: handleSetRate
      file: ./src/cdp/AMM.ts
  - kind: ethereum
    name: AMM-4
    network: optimism
    source:
      address: "0xde18225b337337Bc94bcc7886EF55689C99208f4"
      abi: AMM
      startBlock: 126449751
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - TokenExchange
        - DepositAMM
        - WithdrawAMM
        - SetRate
      abis:
        - name: AMM
          file: ./abis/cdp/AMM.json
      eventHandlers:
        - event: TokenExchange(indexed address,uint256,uint256,uint256,uint256)
          handler: handleTokenExchange
        - event: Deposit(indexed address,uint256,int256,int256)
          handler: handleDeposit
        - event: Withdraw(indexed address,uint256,uint256)
          handler: handleWithdraw
        - event: SetRate(uint256,uint256,uint256)
          handler: handleSetRate
      file: ./src/cdp/AMM.ts
  - kind: ethereum
    name: BoostedStaker-0
    network: optimism
    source:
      address: "0x7e803F4edd6528caFBf5C5d03Cc106b04379C24b"
      abi: BoostedStaker
      startBlock: 121877058
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        # - AccountWeightUpdated
        # - ApprovedUnstakerSet
        # - LocksDisabled
        - Staked
        - Unstaked
      abis:
        - name: BoostedStaker
          file: ./abis/BoostedStaker.json
      eventHandlers:
        # - event: AccountWeightUpdated(indexed address,indexed uint256,uint256,uint256)
        #   handler: handleAccountWeightUpdated
        # - event: ApprovedUnstakerSet(indexed address,indexed address,bool)
        #   handler: handleApprovedUnstakerSet
        # - event: LocksDisabled()
        #   handler: handleLocksDisabled
        - event: Staked(indexed address,indexed uint256,uint256,uint256,bool)
          handler: handleStaked
        - event: Unstaked(indexed address,indexed uint256,uint256,uint256)
          handler: handleUnstaked
      file: ./src/BoostedStaker.ts
  - kind: ethereum
    name: BoostedStaker-1
    network: optimism
    source:
      address: "0xE8f00491afa68B4A653C77e5f92DBA0F8df3a185"
      abi: BoostedStaker
      startBlock: 121877878
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        # - AccountWeightUpdated
        # - ApprovedUnstakerSet
        # - LocksDisabled
        - Staked
        - Unstaked
      abis:
        - name: BoostedStaker
          file: ./abis/BoostedStaker.json
      eventHandlers:
        # - event: AccountWeightUpdated(indexed address,indexed uint256,uint256,uint256)
        #   handler: handleAccountWeightUpdated
        # - event: ApprovedUnstakerSet(indexed address,indexed address,bool)
        #   handler: handleApprovedUnstakerSet
        # - event: LocksDisabled()
        #   handler: handleLocksDisabled
        - event: Staked(indexed address,indexed uint256,uint256,uint256,bool)
          handler: handleStaked
        - event: Unstaked(indexed address,indexed uint256,uint256,uint256)
          handler: handleUnstaked
      file: ./src/BoostedStaker.ts
  - kind: ethereum
    name: BoostedStaker-2
    network: optimism
    source:
      address: "0xa398a48C2738fd6c79F5654823Fb93456B0fDaF6"
      abi: BoostedStaker
      startBlock: 121877633
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        # - AccountWeightUpdated
        # - ApprovedUnstakerSet
        # - LocksDisabled
        - Staked
        - Unstaked
      abis:
        - name: BoostedStaker
          file: ./abis/BoostedStaker.json
      eventHandlers:
        # - event: AccountWeightUpdated(indexed address,indexed uint256,uint256,uint256)
        #   handler: handleAccountWeightUpdated
        # - event: ApprovedUnstakerSet(indexed address,indexed address,bool)
        #   handler: handleApprovedUnstakerSet
        # - event: LocksDisabled()
        #   handler: handleLocksDisabled
        - event: Staked(indexed address,indexed uint256,uint256,uint256,bool)
          handler: handleStaked
        - event: Unstaked(indexed address,indexed uint256,uint256,uint256)
          handler: handleUnstaked
      file: ./src/BoostedStaker.ts
  - kind: ethereum
    name: BoostedStaker-3
    network: optimism
    source:
      address: "0x36afCD1083eE9186A2b984E10d75C1E14b99B75e"
      abi: BoostedStaker
      startBlock: 121877633
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        # - AccountWeightUpdated
        # - ApprovedUnstakerSet
        # - LocksDisabled
        - Staked
        - Unstaked
      abis:
        - name: BoostedStaker
          file: ./abis/BoostedStaker.json
      eventHandlers:
        # - event: AccountWeightUpdated(indexed address,indexed uint256,uint256,uint256)
        #   handler: handleAccountWeightUpdated
        # - event: ApprovedUnstakerSet(indexed address,indexed address,bool)
        #   handler: handleApprovedUnstakerSet
        # - event: LocksDisabled()
        #   handler: handleLocksDisabled
        - event: Staked(indexed address,indexed uint256,uint256,uint256,bool)
          handler: handleStaked
        - event: Unstaked(indexed address,indexed uint256,uint256,uint256)
          handler: handleUnstaked
      file: ./src/BoostedStaker.ts
  - kind: ethereum
    name: BoostedStaker-4
    network: optimism
    source:
      address: "0xcf38a66DeD7825cfEF66046c256Aa0EDbd41BEf5"
      abi: BoostedStaker
      startBlock: 121877747
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        # - AccountWeightUpdated
        # - ApprovedUnstakerSet
        # - LocksDisabled
        - Staked
        - Unstaked
      abis:
        - name: BoostedStaker
          file: ./abis/BoostedStaker.json
      eventHandlers:
        # - event: AccountWeightUpdated(indexed address,indexed uint256,uint256,uint256)
        #   handler: handleAccountWeightUpdated
        # - event: ApprovedUnstakerSet(indexed address,indexed address,bool)
        #   handler: handleApprovedUnstakerSet
        # - event: LocksDisabled()
        #   handler: handleLocksDisabled
        - event: Staked(indexed address,indexed uint256,uint256,uint256,bool)
          handler: handleStaked
        - event: Unstaked(indexed address,indexed uint256,uint256,uint256)
          handler: handleUnstaked
      file: ./src/BoostedStaker.ts
  - kind: ethereum
    name: BoostedStaker-5
    network: optimism
    source:
      address: "0x73C3eC2b8e00929824a529e60fb6ed8aF193c7cc"
      abi: BoostedStaker
      startBlock: 121877790
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        # - AccountWeightUpdated
        # - ApprovedUnstakerSet
        # - LocksDisabled
        - Staked
        - Unstaked
      abis:
        - name: BoostedStaker
          file: ./abis/BoostedStaker.json
      eventHandlers:
        # - event: AccountWeightUpdated(indexed address,indexed uint256,uint256,uint256)
        #   handler: handleAccountWeightUpdated
        # - event: ApprovedUnstakerSet(indexed address,indexed address,bool)
        #   handler: handleApprovedUnstakerSet
        # - event: LocksDisabled()
        #   handler: handleLocksDisabled
        - event: Staked(indexed address,indexed uint256,uint256,uint256,bool)
          handler: handleStaked
        - event: Unstaked(indexed address,indexed uint256,uint256,uint256)
          handler: handleUnstaked
      file: ./src/BoostedStaker.ts
